name              'workstation-cookbook'
maintainer        'Gregory Damiani'
maintainer_email  'gregory.damiani@gmail.com'
license           'All rights reserved'
description       'Configures a Mac workstation'
long_description  'Configures a Mac workstation'
version           '0.1.0'

depends           'build-essential', '6.0.0'
depends           'dmg', '2.4.0'
depends           'git', '4.6.0'
depends           'chef-dk', '3.1.0'
depends           'python', '1.4.0'
depends           'homebrew', '2.1.0'
